// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto

/*
Package go_micro_service_order is a generated protocol buffer package.

It is generated from these files:
	proto/order/order.proto

It has these top-level messages:
	AllOrderRequest
	AllOrder
	OrderID
	OrderInfo
	OrderDetail
	Response
	PayStatus
	ShipStatus
*/
package go_micro_service_order

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AllOrderRequest struct {
}

func (m *AllOrderRequest) Reset()                    { *m = AllOrderRequest{} }
func (m *AllOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*AllOrderRequest) ProtoMessage()               {}
func (*AllOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AllOrder struct {
	OrderInfo []*OrderInfo `protobuf:"bytes,1,rep,name=order_info,json=orderInfo" json:"order_info,omitempty"`
}

func (m *AllOrder) Reset()                    { *m = AllOrder{} }
func (m *AllOrder) String() string            { return proto.CompactTextString(m) }
func (*AllOrder) ProtoMessage()               {}
func (*AllOrder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AllOrder) GetOrderInfo() []*OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

type OrderID struct {
	OrderId int64 `protobuf:"varint,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
}

func (m *OrderID) Reset()                    { *m = OrderID{} }
func (m *OrderID) String() string            { return proto.CompactTextString(m) }
func (*OrderID) ProtoMessage()               {}
func (*OrderID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OrderID) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type OrderInfo struct {
	Id          int64          `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	PayStatus   int32          `protobuf:"varint,2,opt,name=pay_status,json=payStatus" json:"pay_status,omitempty"`
	ShipStatus  int32          `protobuf:"varint,3,opt,name=ship_status,json=shipStatus" json:"ship_status,omitempty"`
	Price       float64        `protobuf:"fixed64,4,opt,name=price" json:"price,omitempty"`
	OrderDetail []*OrderDetail `protobuf:"bytes,5,rep,name=order_detail,json=orderDetail" json:"order_detail,omitempty"`
}

func (m *OrderInfo) Reset()                    { *m = OrderInfo{} }
func (m *OrderInfo) String() string            { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()               {}
func (*OrderInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OrderInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderInfo) GetPayStatus() int32 {
	if m != nil {
		return m.PayStatus
	}
	return 0
}

func (m *OrderInfo) GetShipStatus() int32 {
	if m != nil {
		return m.ShipStatus
	}
	return 0
}

func (m *OrderInfo) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderInfo) GetOrderDetail() []*OrderDetail {
	if m != nil {
		return m.OrderDetail
	}
	return nil
}

type OrderDetail struct {
	Id            int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	ProductId     int64 `protobuf:"varint,2,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	ProductNum    int64 `protobuf:"varint,3,opt,name=product_num,json=productNum" json:"product_num,omitempty"`
	ProductSizeId int64 `protobuf:"varint,4,opt,name=product_size_id,json=productSizeId" json:"product_size_id,omitempty"`
	ProductPrice  int64 `protobuf:"varint,5,opt,name=product_price,json=productPrice" json:"product_price,omitempty"`
	OrderId       int64 `protobuf:"varint,6,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
}

func (m *OrderDetail) Reset()                    { *m = OrderDetail{} }
func (m *OrderDetail) String() string            { return proto.CompactTextString(m) }
func (*OrderDetail) ProtoMessage()               {}
func (*OrderDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OrderDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderDetail) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *OrderDetail) GetProductNum() int64 {
	if m != nil {
		return m.ProductNum
	}
	return 0
}

func (m *OrderDetail) GetProductSizeId() int64 {
	if m != nil {
		return m.ProductSizeId
	}
	return 0
}

func (m *OrderDetail) GetProductPrice() int64 {
	if m != nil {
		return m.ProductPrice
	}
	return 0
}

func (m *OrderDetail) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PayStatus struct {
	OrderId   int64 `protobuf:"varint,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	PayStatus int32 `protobuf:"varint,2,opt,name=pay_status,json=payStatus" json:"pay_status,omitempty"`
}

func (m *PayStatus) Reset()                    { *m = PayStatus{} }
func (m *PayStatus) String() string            { return proto.CompactTextString(m) }
func (*PayStatus) ProtoMessage()               {}
func (*PayStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PayStatus) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *PayStatus) GetPayStatus() int32 {
	if m != nil {
		return m.PayStatus
	}
	return 0
}

type ShipStatus struct {
	OrderId    int64 `protobuf:"varint,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	ShipStatus int32 `protobuf:"varint,2,opt,name=ship_status,json=shipStatus" json:"ship_status,omitempty"`
}

func (m *ShipStatus) Reset()                    { *m = ShipStatus{} }
func (m *ShipStatus) String() string            { return proto.CompactTextString(m) }
func (*ShipStatus) ProtoMessage()               {}
func (*ShipStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ShipStatus) GetOrderId() int64 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *ShipStatus) GetShipStatus() int32 {
	if m != nil {
		return m.ShipStatus
	}
	return 0
}

func init() {
	proto.RegisterType((*AllOrderRequest)(nil), "go.micro.service.order.AllOrderRequest")
	proto.RegisterType((*AllOrder)(nil), "go.micro.service.order.AllOrder")
	proto.RegisterType((*OrderID)(nil), "go.micro.service.order.OrderID")
	proto.RegisterType((*OrderInfo)(nil), "go.micro.service.order.OrderInfo")
	proto.RegisterType((*OrderDetail)(nil), "go.micro.service.order.OrderDetail")
	proto.RegisterType((*Response)(nil), "go.micro.service.order.Response")
	proto.RegisterType((*PayStatus)(nil), "go.micro.service.order.PayStatus")
	proto.RegisterType((*ShipStatus)(nil), "go.micro.service.order.ShipStatus")
}

func init() { proto.RegisterFile("proto/order/order.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x8d, 0xed, 0xb8, 0x8d, 0xc7, 0xf9, 0xbe, 0xc0, 0xaa, 0x80, 0x89, 0x40, 0x35, 0x5b, 0x04,
	0xb9, 0x32, 0x52, 0x79, 0x01, 0x7e, 0x0c, 0x25, 0x12, 0x82, 0xca, 0x29, 0x5c, 0x20, 0xa1, 0xc8,
	0x64, 0xb7, 0x65, 0xa5, 0x24, 0x6b, 0xbc, 0x6b, 0xa4, 0xf4, 0xcd, 0x78, 0x00, 0xde, 0x8a, 0x0b,
	0xe4, 0xb5, 0xd7, 0x31, 0x51, 0x1d, 0xfb, 0x26, 0x1a, 0x9f, 0x39, 0x73, 0xf6, 0xcc, 0xce, 0x6c,
	0xe0, 0x5e, 0x92, 0x72, 0xc9, 0x9f, 0xf1, 0x94, 0xd0, 0xb4, 0xf8, 0x0d, 0x14, 0x82, 0xee, 0x5e,
	0xf1, 0x60, 0xc5, 0x16, 0x29, 0x0f, 0x04, 0x4d, 0x7f, 0xb2, 0x05, 0x0d, 0x54, 0x16, 0xdf, 0x86,
	0xd1, 0xcb, 0xe5, 0xf2, 0x63, 0x1e, 0x47, 0xf4, 0x47, 0x46, 0x85, 0xc4, 0xef, 0x61, 0xa0, 0x21,
	0xf4, 0x02, 0x40, 0xf1, 0xe6, 0x6c, 0x7d, 0xc9, 0x3d, 0xc3, 0xb7, 0x26, 0xee, 0xe9, 0xa3, 0xe0,
	0x66, 0xad, 0x40, 0x95, 0x4c, 0xd7, 0x97, 0x3c, 0x72, 0xb8, 0x0e, 0xf1, 0x63, 0x38, 0x2c, 0xf0,
	0x10, 0xdd, 0x87, 0x41, 0x29, 0x46, 0x3c, 0xc3, 0x37, 0x26, 0x56, 0x74, 0x58, 0xf0, 0x08, 0xfe,
	0x65, 0x80, 0x53, 0x95, 0xa3, 0xff, 0xc1, 0xac, 0x28, 0x26, 0x23, 0xe8, 0x21, 0x40, 0x12, 0x6f,
	0xe6, 0x42, 0xc6, 0x32, 0x13, 0x9e, 0xe9, 0x1b, 0x13, 0x3b, 0x72, 0x92, 0x78, 0x33, 0x53, 0x00,
	0x3a, 0x06, 0x57, 0x7c, 0x67, 0x89, 0xce, 0x5b, 0x2a, 0x0f, 0x39, 0x54, 0x12, 0x8e, 0xc0, 0x4e,
	0x52, 0xb6, 0xa0, 0x5e, 0xdf, 0x37, 0x26, 0x46, 0x54, 0x7c, 0xa0, 0xb7, 0x30, 0x2c, 0xec, 0x10,
	0x2a, 0x63, 0xb6, 0xf4, 0x6c, 0xd5, 0xdd, 0xc9, 0xde, 0xee, 0x42, 0x45, 0x8d, 0x5c, 0xbe, 0xfd,
	0xc0, 0xbf, 0x0d, 0x70, 0x6b, 0xc9, 0x1b, 0xdd, 0xa7, 0x9c, 0x64, 0x0b, 0x99, 0x37, 0x6e, 0x2a,
	0xdc, 0x29, 0x91, 0x29, 0xc9, 0xdd, 0xeb, 0xf4, 0x3a, 0x5b, 0x29, 0xf7, 0x56, 0xa4, 0x2b, 0x3e,
	0x64, 0x2b, 0xf4, 0x04, 0x46, 0x9a, 0x20, 0xd8, 0x35, 0xcd, 0x45, 0xfa, 0x8a, 0xf4, 0x5f, 0x09,
	0xcf, 0xd8, 0x35, 0x9d, 0x12, 0x74, 0x02, 0x1a, 0x98, 0x17, 0xdd, 0xda, 0x8a, 0x35, 0x2c, 0xc1,
	0x73, 0xd5, 0x74, 0x7d, 0x06, 0x07, 0xff, 0xce, 0xe0, 0x01, 0x0c, 0x22, 0x2a, 0x12, 0xbe, 0x16,
	0x14, 0xdd, 0x02, 0x6b, 0x25, 0xae, 0x54, 0x13, 0x4e, 0x94, 0x87, 0xf8, 0x0d, 0x38, 0xe7, 0xd5,
	0x8d, 0x37, 0x4f, 0xb2, 0x65, 0x56, 0xf8, 0x1d, 0xc0, 0x6c, 0x3b, 0x98, 0x3d, 0x3a, 0x3b, 0x43,
	0x35, 0x77, 0x87, 0x7a, 0xfa, 0xa7, 0x0f, 0x76, 0xb1, 0xa4, 0x17, 0x30, 0x3c, 0xa3, 0x52, 0xc5,
	0xaf, 0x36, 0xd3, 0x10, 0x1d, 0xef, 0x5f, 0xd0, 0x70, 0xdc, 0xbe, 0xc1, 0xb8, 0x87, 0xbe, 0x80,
	0x7b, 0x46, 0x65, 0xf5, 0x12, 0x9e, 0x36, 0xd5, 0xec, 0x3c, 0x9f, 0xb1, 0xdf, 0x46, 0xc4, 0x3d,
	0x34, 0x03, 0xf7, 0x75, 0x4a, 0x63, 0x49, 0x0b, 0xed, 0x76, 0x3f, 0xe3, 0xb6, 0x9e, 0x70, 0x0f,
	0x7d, 0x86, 0x51, 0x48, 0x97, 0xb4, 0x14, 0xed, 0x76, 0x13, 0x8d, 0x66, 0xf5, 0x26, 0xe0, 0x1e,
	0xfa, 0x0a, 0x47, 0x9f, 0x12, 0xa2, 0xcd, 0x6e, 0x97, 0xa0, 0xd1, 0x75, 0x45, 0xe9, 0x24, 0x3f,
	0x87, 0x3b, 0x35, 0xf9, 0xda, 0x72, 0xe0, 0xa6, 0xe2, 0x2d, 0xa7, 0xd3, 0x01, 0x17, 0xe0, 0xd6,
	0x0e, 0xe8, 0x72, 0xd9, 0x1d, 0x54, 0xbf, 0x1d, 0xa8, 0xff, 0xd5, 0xe7, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xf3, 0x13, 0xb4, 0x23, 0x72, 0x05, 0x00, 0x00,
}
